FROM python:3.10

# Install other dependencies
RUN pip install --upgrade pip

# Create a directory for the application
RUN mkdir /app

# Set the working directory
WORKDIR /app

# Copy and install the requirements
COPY requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

# Copy the application code to the image
COPY . /app/

# Define environment variables
ENV dash_port=80
ENV dash_debug="False"

CMD [python main.py"]
